version: '3'

services:
  ocuro:
    build:
      context: .
    image: ab/ocuro:latest
    container_name: ocuro
    ports:
      - "127.0.10.100:3000:3000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
      # - .env.local

networks:
  default:
    name: scoobydoo
    external: true
